USE [Turism]
GO

/****** Object:  Database [TURagenstvo]    Script Date: 13.11.2024 15:02:41 ******/


IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TURagenstvo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TURagenstvo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TURagenstvo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TURagenstvo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TURagenstvo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TURagenstvo] SET ARITHABORT OFF 
GO

ALTER DATABASE [TURagenstvo] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TURagenstvo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TURagenstvo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TURagenstvo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TURagenstvo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TURagenstvo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TURagenstvo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TURagenstvo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TURagenstvo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TURagenstvo] SET  ENABLE_BROKER 
GO

ALTER DATABASE [TURagenstvo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TURagenstvo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TURagenstvo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TURagenstvo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TURagenstvo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TURagenstvo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TURagenstvo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TURagenstvo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TURagenstvo] SET  MULTI_USER 
GO

ALTER DATABASE [TURagenstvo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TURagenstvo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TURagenstvo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TURagenstvo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TURagenstvo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TURagenstvo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TURagenstvo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TURagenstvo] SET  READ_WRITE 
GO

