//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dem_exam_Tourizm_Fedchenko.Model
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.Hotel = new HashSet<Hotel>();
            this.Type = new HashSet<Type>();
        }
    
        public int Id { get; set; }
        public int TicketCount { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImagePreview { get; set; }
        public decimal Price { get; set; }
        public bool IsActual { get; set; }

        public string ActualStatus
        {
            get
            {
                return (IsActual) ? "Актуален" : "Не актуален";
            }
        }

        public SolidColorBrush colorBrush
        {
            get
            {
                if (this.IsActual)
                {
                    return Brushes.Green;
                }
                else
                {
                    return Brushes.Red;
                }
            }
        }

        public string TourPhoto
        {
            get
            {
                return $"/Resources/{ImagePreview}.jpg";
            }
        }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hotel> Hotel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Type> Type { get; set; }
    }
}
